### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by 316austin316** [ascomods/game-assets-converter#1]
![build issue](https://github.com/ascomods/game-assets-converter/assets/115892533/466ae371-c273-4c0e-be63-9446e0c1a522)
Trying to build the program with my modifications keeps leading to this issue. I see you have provided the python fbx.pyd but it does not seem to function? Says there is no module named fbx to import.... in the module named fbx.py.. do you have any clarification on build instructions?

**Comment by ascomods** [comment]
Late reply, I didn't see the issue. Basically it depends on your python installation. You could add the fbx lib files globally but I've updated the readme, showing how to install the app in a virtual environnement and where to copy the fbx lib files. Closing the issue.
